// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg5dU1sEN46ql7xnm3nzIjjFC6A8YxegY',
    appId: '1:383502342599:web:820396b8bb5f1eb448a1e2',
    messagingSenderId: '383502342599',
    projectId: 'scholar-app-b9dfc',
    authDomain: 'scholar-app-b9dfc.firebaseapp.com',
    storageBucket: 'scholar-app-b9dfc.appspot.com',
    measurementId: 'G-GZC06437YM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK37Nm59q78lxKxMLbCnnTwz3gHL_2UOY',
    appId: '1:383502342599:android:6043414c39e9ca1e48a1e2',
    messagingSenderId: '383502342599',
    projectId: 'scholar-app-b9dfc',
    storageBucket: 'scholar-app-b9dfc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVpmNOCIfauPgsJAMYeo7kDkI6Am_WUCM',
    appId: '1:383502342599:ios:bbd6d73a7788de1448a1e2',
    messagingSenderId: '383502342599',
    projectId: 'scholar-app-b9dfc',
    storageBucket: 'scholar-app-b9dfc.appspot.com',
    iosClientId: '383502342599-024fcddgqtan53vjrv2e95fpa4vbuvel.apps.googleusercontent.com',
    iosBundleId: 'com.example.scholarChat',
  );
}
