// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApcCIWhSoc0xLBD-WuH8DdrBpk2HMVRkA',
    appId: '1:42150383649:web:bee4bf9d0f6ee0b9f3d360',
    messagingSenderId: '42150383649',
    projectId: 'chat-app-fa47b',
    authDomain: 'chat-app-fa47b.firebaseapp.com',
    storageBucket: 'chat-app-fa47b.appspot.com',
    measurementId: 'G-RNB9053XWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsnxfZrD8Ql37Fxtxr7E7xUon9cy-ztSg',
    appId: '1:42150383649:android:cd993c38bcb8883af3d360',
    messagingSenderId: '42150383649',
    projectId: 'chat-app-fa47b',
    storageBucket: 'chat-app-fa47b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiWEuW_x1FruR4DfLYdCOHtpqEx3R-JzY',
    appId: '1:42150383649:ios:d7eaf17c3e52b1d2f3d360',
    messagingSenderId: '42150383649',
    projectId: 'chat-app-fa47b',
    storageBucket: 'chat-app-fa47b.appspot.com',
    iosClientId: '42150383649-3rol9j0n36orrv0lf983ro2thgahq1k7.apps.googleusercontent.com',
    iosBundleId: 'com.example.scholarChat',
  );
}
